name: "action"
description: ""
author: "ian lewis"
inputs:
  slsa-workflow-inputs:
    description: "All the inputs formatted as a JSON map"
    required: true

  slsa-layout-file:
    description: "Location to store the layout content"
    required: true

  # Unused secret inputs.
  slsa-workflow-secret1: {}
  slsa-workflow-secret2: {}
  slsa-workflow-secret3: {}
  slsa-workflow-secret4: {}
  slsa-workflow-secret5: {}
  slsa-workflow-secret6: {}
  slsa-workflow-secret7: {}
  slsa-workflow-secret8: {}
  slsa-workflow-secret9: {}
  slsa-workflow-secret10: {}
  slsa-workflow-secret11: {}
  slsa-workflow-secret12: {}
  slsa-workflow-secret13: {}
  slsa-workflow-secret14: {}
  slsa-workflow-secret15: {}

runs:
  using: "node16"
  main: "src/index.js"
