name: BYOB template
on:
  workflow_dispatch:
  # push:
  #   tags:
  #     - "*"

permissions: read-all

jobs:
  build:
    permissions:
      id-token: write # For signing
      # actions: read
      contents: write # For asset uploads
      packages: write # To write to github packages
    uses: ianlewis/slsa-byob-template/.github/workflows/slsa3.yml@main
    with:
      message: "Hello World!"
      file: hello.txt
      # version: v0.0.2
