name: Node.js
on:
  workflow_dispatch:
  push:
    tags:
      - "*"

permissions: read-all

jobs:
  build:
    permissions:
      id-token: write # For signing
      # actions: read
      contents: write # For asset uploads
      packages: write # To write to github packages
    uses: ianlewis/slsa-github-generator/.github/workflows/builder_nodejs_slsa3.yml@nodejs-v02
    with:
      directory: nodejs
      node-version: 16
      run-scripts: "build"
