name: Node.js
on:
  workflow_dispatch:
    push:
      tags:
        - "*"

permissions: read-all

jobs:
  build:
    permissions:
      id-token: write # For signing
      # actions: read
      contents: write # For asset uploads
      packages: write # To write to github packages
    uses: ianlewis/slsa-github-generator/.github/workflows/builder_nodejs_slsa3.yml@nodejs-outputs
    with:
      directory: nodejs
      node-version: 16
      run-scripts: "ci, build"
      access: public
      dist-tag: foo
    secrets:
      node-auth-token: ${{ secrets.NPM_TOKEN }}

  print-outputs:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Print outputs
        shell: bash
        env:
          OUTPUTS: "${{ toJSON(needs.build.outputs) }}"
        run: echo "${OUTPUTS}"
