name: Node.js
on:
  workflow_dispatch:
  push:
    tags:
      - "*"

permissions: read-all

jobs:
  build:
    permissions:
      id-token: write # For signing
      contents: read # For repo checkout.
      actions: read # For getting workflow run info.
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_nodejs_slsa3.yml@v1.7.0
    # uses: ianlewis/slsa-github-generator/.github/workflows/builder_nodejs_slsa3.yml@npm-upstream
    with:
      directory: nodejs
      node-version: 16
      run-scripts: "ci, build"
      rekor-log-public: true

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node environment
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"

      - name: publish
        id: publish
        # uses: slsa-framework/slsa-github-generator/actions/nodejs/publish@v1.6.0
        uses: ianlewis/slsa-github-generator/actions/nodejs/publish@npm-upstream
        with:
          access: public
          node-auth-token: ${{ secrets.NPM_TOKEN }}
          package-name: ${{ needs.build.outputs.package-name }}
          package-download-name: ${{ needs.build.outputs.package-download-name }}
          package-download-sha256: ${{ needs.build.outputs.package-download-sha256 }}
          provenance-name: ${{ needs.build.outputs.provenance-name }}
          provenance-download-name: ${{ needs.build.outputs.provenance-download-name }}
          provenance-download-sha256: ${{ needs.build.outputs.provenance-download-sha256 }}

      - name: Print outputs
        shell: bash
        env:
          BUILD_OUTPUTS: "${{ toJSON(needs.build.outputs) }}"
          PUBLISH_OUTPUTS: "${{ toJSON(steps.publish.outputs) }}"
        run: |
          echo "build:   ${BUILD_OUTPUTS}"
          echo "publish: ${PUBLISH_OUTPUTS}"
