name: Node.js
on:
  workflow_dispatch:
  push:
    tags:
      - "*"

permissions: read-all

jobs:
  build:
    permissions:
      id-token: write # For signing
      contents: read # For repo checkout.
      actions: read # For getting workflow run info.
    # uses: ianlewis/slsa-github-generator/.github/workflows/builder_nodejs_slsa3.yml@low-perms-delegator
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_nodejs_slsa3.yml@main
    with:
      directory: nodejs
      node-version: 16
      run-scripts: "ci, build"
      rekor-log-public: true
    secrets:
      node-auth-token: ${{ secrets.NPM_TOKEN }}

  print-outputs:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Print outputs
        shell: bash
        env:
          OUTPUTS: "${{ toJSON(needs.build.outputs) }}"
        run: echo "${OUTPUTS}"
