name: SLSA provenance
on:
  workflow_dispatch:
  push:
    tags:
      - "*"

permissions: read-all

jobs:
  provenance:
    permissions:
      id-token: write
      contents: read
    uses: ianlewis/slsa-github-generator/.github/workflows/provenance.yml@slsa-gen-lib-ianlewis
    with:
      artifacts: "actions-test:2e0390eb024a52963db7b95e84a9c2b12c004054a7bad9a97ec0c7c89d4681d2"
