name: SLSA provenance
on:
  workflow_dispatch:
  push:
    tags:
      - "*"

permissions: read-all

jobs:
  hash:
    outputs:
      digest: ${{ steps.hash.outputs.digest }}
    runs-on: ubuntu-latest
      - name: hash
        shell: bash
        id: hash
        run: |
            set -euo pipefail
            echo "hoge" > hoge
            echo "fuga" > fuga
            DIGEST=$(sha256sum hoge fuga)
            DIGEST="${DIGEST//'%'/'%25'}"
            DIGEST="${DIGEST//$'\n'/'%0A'}"
            DIGEST="${DIGEST//$'\r'/'%0D'}"
            echo "::set-output name=digest::$DIGEST"
  provenance:
    permissions:
      id-token: write
      contents: read
    uses: ianlewis/slsa-github-generator/.github/workflows/provenance.yml@slsa-gen-lib
    with:
      subjects: "${{ jobs.hash.outputs.digest }}"
