name: SLSA provenance
on:
  workflow_dispatch:
  push:
    tags:
      - "*"

permissions: read-all

jobs:
  provenance:
    permissions:
      id-token: write
      contents: read
    uses: ianlewis/slsa-github-generator/.github/workflows/provenance.yml@slsa-gen-lib
    with:
      subjects: "actions-test@somesha"
