name: test
on:
  workflow_dispatch:

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - shell: node
        run: |
          let x = {
            foo: "bar",
          }
      - uses: ./action
        with:
          foo: ${{ x.foo }}
          bar: ${{ x.bar }}
          hoge: ${{ x.hoge }}
