name: test
on:
  workflow_dispatch:

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      # - uses: ianlewis/slsa-github-generator/.github/actions/secure-checkout@secure-checkout-ref
      - uses: ianlewis/slsa-github-generator/.github/actions/checkout-go@checkout-ref
      - uses: ianlewis/slsa-github-generator/.github/actions/checkout-node@checkout-ref
