name: test
on:
  workflow_dispatch:

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - shell: node
        run: |
          import * as fs from 'fs'
          import * as os from 'os'

          let x = { foo: "bar" }
          let outValue = JSON.stringify(x)

          fs.appendFileSync(process.env.GITHUB_OUTPUT, `action-inputs=${outValue}${os.EOL}`, {
            encoding: 'utf8'
          })
      - uses: ./action
        with:
          foo: ${{ x.foo }}
          bar: ${{ x.bar }}
          hoge: ${{ x.hoge }}
