name: test
on:
  workflow_dispatch:

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - shell: node
        id: inputs
        run: |
          import * as fs from 'fs'
          import * as os from 'os'

          let x = { foo: "bar" }
          let outValue = JSON.stringify(x)

          fs.appendFileSync(process.env.GITHUB_OUTPUT, `inputs=${outValue}${os.EOL}`, {
            encoding: 'utf8'
          })
      - uses: ./action
        with:
          foo: ${{ fromJSON(steps.inputs.outputs.inputs).foo }}
          bar: ${{ fromJSON(steps.inputs.outputs.inputs).bar }}
          hoge: ${{ fromJSON(steps.inputs.outputs.inputs).hoge }}
