name: test
on:
  workflow_dispatch:

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - shell: python
        id: inputs
        run: |
          import os, json
          x = { "foo": "bar" }
          with open(os.environ["GITHUB_OUTPUT"], "a") as github_output:
            github_output.write("inputs=%s\n" % json.dumps(x))

      - uses: ./action
        with:
          foo: ${{ fromJSON(steps.inputs.outputs.inputs).foo }}
          bar: ${{ fromJSON(steps.inputs.outputs.inputs).bar }}
          hoge: ${{ fromJSON(steps.inputs.outputs.inputs).hoge }}
